/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6 */

#ifndef PB_DATA_MSG_PB_H_INCLUDED
#define PB_DATA_MSG_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _beacon_msg { 
    uint32_t uav_type;
    double GPS[2];
} beacon_msg;

typedef struct _ranging_response_msg { 
    uint32_t delay;
} ranging_response_msg;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define beacon_msg_init_default                  {0, {0, 0}}
#define ranging_response_msg_init_default        {0}
#define beacon_msg_init_zero                     {0, {0, 0}}
#define ranging_response_msg_init_zero           {0}

/* Field tags (for use in manual encoding/decoding) */
#define beacon_msg_uav_type_tag                  1
#define beacon_msg_GPS_tag                       2
#define ranging_response_msg_delay_tag           1

/* Struct field encoding specification for nanopb */
#define beacon_msg_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   uav_type,          1) \
X(a, STATIC,   FIXARRAY, DOUBLE,   GPS,               2)
#define beacon_msg_CALLBACK NULL
#define beacon_msg_DEFAULT NULL

#define ranging_response_msg_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   delay,             1)
#define ranging_response_msg_CALLBACK NULL
#define ranging_response_msg_DEFAULT NULL

extern const pb_msgdesc_t beacon_msg_msg;
extern const pb_msgdesc_t ranging_response_msg_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define beacon_msg_fields &beacon_msg_msg
#define ranging_response_msg_fields &ranging_response_msg_msg

/* Maximum encoded size of messages (where known) */
#define beacon_msg_size                          24
#define ranging_response_msg_size                6

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
